-- Script that creates the datbase hbnt_0d_usa and the table cities on the server
-- Description: id=INT unique, autogenerated, cant be null and is a primary key, state_id=INT cant be null and must be a foreign key that references to id of the state table, name=VARCHAR(256)
-- If the database and the table already exists the script should not fail

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities(
	id INT AUTO_INCREMENT PRIMARY KEY,
	state_id INT,
	FOREIGN KEY (state_id) REFERENCES hbnt_0d_usa.states(id),
	name VARCHAR(256) NOT NULL
	);
